### ISSUE TITLE
GitHub Action build - Allow.XXXX values not available

### ISSUE THREAD

**Issue by kevinvenclovas** [FastEndpoints/FastEndpoints#702]
Hi,

I am currently trying to build my .NET application using GitHub Actions, but during the build process, the application cannot find my custom Allow.XXXX values.

How can I generate the Allow file during the build process?

Thank you for your assistance.

Added custom `Allow.Health` value like this
```c#
AccessControl(
  "Authentication_Show_Permissions",
  Apply.ToThisEndpoint,
  "Health"
);

```

`"Allow" does not contain a definition for "Health"`

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/b2fd4bf0-3895-41da-ad3a-788d0df972c9)

```
name: Deploy Dev

on: [push]

jobs:
  deploy-dev:
    runs-on: self-hosted
    
    env:
      DOTNET_INSTALL_DIR: 'C:/actions-runner/dotnet'
 
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore .\XXX
      
      - name: Build with dotnet
        run: dotnet build --no-restore --configuration Release .\XXX
```
